ZEN-826 Google sign-in plugin
PushkinStudio/PsAndroidGamesSignIn pull request #1
Opened 2019-04-29 17:08 UTC by Antonrr

2019-04-29 17:22 UTC, ufna commented
+ надо добавить clang-format файл (и чекнуть что все под ним норм)

2019-04-29 17:22 UTC, ufna requested changes

2019-04-29 17:22 UTC, ufna commented on Source/PsAndroidGamesSignIn/Private/Android/PsGoogleLogin.java
> +package com.pushkinstudio.PsAndroidGamesSignIn;
Добавь сюда также копирайты

2019-04-29 17:22 UTC, ufna commented on Source/PsAndroidGamesSignIn/PsAndroidGamesSignIn_UPL_Android.xml
> +					mPsGoogleLogin.SignInSilently();
может тут вызывать без проверки, либо кидать эксепшн? Потому что поведение "объект не создался, а мы тихо проигнорировали" - имхо слишком скрыто

2019-04-29 17:22 UTC, ufna commented on Source/PsAndroidGamesSignIn/Public/PsAndroidGamesSignIn.h
> +#define PS_FUNC (FString(__FUNCTION__))
Вот это я бы вынес в дефайнзм как мы по-классике делаем. Либо в модуль накрайняк

2019-04-30 07:39 UTC, Antonrr commented on Source/PsAndroidGamesSignIn/Public/PsAndroidGamesSignIn.h
> +#define PS_FUNC (FString(__FUNCTION__))
Я подумал, что не стоит делать отдельный файл с дефайнами, если весь плагин — это один класс-библиотека функций. Может, и правда в модуль перенести?

2019-04-30 07:40 UTC, Antonrr commented on Source/PsAndroidGamesSignIn/PsAndroidGamesSignIn_UPL_Android.xml
> +					mPsGoogleLogin.SignInSilently();
Согласен, уберу проверку, тогда будет кидаться exception.

2019-04-30 08:48 UTC, ufna approved these changes

2019-04-30 08:52 UTC, merged